/**
 * MiniSwapEscrow 배포 스크립트
 *
 * 로컬:   npx hardhat run scripts/deploy.js --network localhost
 * 메인넷: npx hardhat run scripts/deploy.js --network arbitrum
 *
 * 배포 후 src/deployments.js 에 주소가 자동 저장됩니다.
 */
const { ethers } = require('hardhat')
const fs   = require('fs')
const path = require('path')

async function main() {
  const signers = await ethers.getSigners()
  const deployer      = signers[0]
  const feeRecipient  = signers[1] || signers[0]
  const admin1        = signers[2] || signers[0]
  const admin2        = signers[3] || signers[0]

  const network  = hre.network.name
  const chainId  = Number((await ethers.provider.getNetwork()).chainId)

  console.log('────────────────────────────────────────')
  console.log('Network      :', network, `(chainId ${chainId})`)
  console.log('Deployer     :', deployer.address)
  console.log('feeRecipient :', feeRecipient.address)
  console.log('admin1       :', admin1.address)
  console.log('admin2       :', admin2.address)
  console.log('────────────────────────────────────────')

  // ── USDT 주소 결정 ────────────────────────────────────────────
  let usdtAddress

  if (network === 'localhost' || network === 'hardhat') {
    console.log('\n[1/3] Deploying MockERC20 (USDT) for local testing...')
    const MockERC20 = await ethers.getContractFactory('MockERC20')
    const mockUsdt  = await MockERC20.deploy('Tether USD', 'USDT', 6)
    await mockUsdt.waitForDeployment()
    usdtAddress = await mockUsdt.getAddress()
    console.log('     MockUSDT  :', usdtAddress)

    // 테스트용 USDT 발행 (각 계정에 10만 USDT)
    for (let i = 0; i < Math.min(signers.length, 5); i++) {
      await mockUsdt.mint(signers[i].address, ethers.parseUnits('100000', 6))
    }
    console.log('     Minted 100,000 USDT to first 5 accounts')

  } else if (network === 'arbitrum') {
    usdtAddress = '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9'
    console.log('\n[1/3] Using Arbitrum One USDT:', usdtAddress)

  } else if (network === 'arbitrumSepolia') {
    usdtAddress = '0x3f14920c99BEB920Afa163031c4e47a3e03B3e4A'
    console.log('\n[1/3] Using Arbitrum Sepolia USDT:', usdtAddress)

  } else {
    throw new Error(`지원하지 않는 네트워크: ${network}`)
  }

  // ── MiniSwapEscrow 배포 ───────────────────────────────────────
  console.log('\n[2/3] Deploying MiniSwapEscrow...')
  const MiniSwapEscrow = await ethers.getContractFactory('MiniSwapEscrow')
  const escrow = await MiniSwapEscrow.deploy(
    usdtAddress,
    feeRecipient.address,
    admin1.address,
    admin2.address
  )
  await escrow.waitForDeployment()
  const escrowAddress = await escrow.getAddress()
  console.log('     MiniSwapEscrow:', escrowAddress)

  // ── src/deployments.js 업데이트 ───────────────────────────────
  console.log('\n[3/3] Saving deployment info to src/deployments.js...')
  const deploymentsPath = path.join(__dirname, '..', 'src', 'deployments.js')

  let existing = {}
  if (fs.existsSync(deploymentsPath)) {
    const content = fs.readFileSync(deploymentsPath, 'utf8')
    const m = content.match(/export const DEPLOYMENTS\s*=\s*(\{[\s\S]*?\});/)
    if (m) {
      try { existing = JSON.parse(m[1]) } catch {}
    }
  }

  existing[chainId] = { escrow: escrowAddress, usdt: usdtAddress }

  const newContent =
    `// Auto-generated by scripts/deploy.js — do not edit manually\n` +
    `export const DEPLOYMENTS = ${JSON.stringify(existing, null, 2)};\n`

  fs.writeFileSync(deploymentsPath, newContent, 'utf8')
  console.log('     Saved!')
  console.log('\n────────────────────────────────────────')
  console.log('Done! Contract addresses:')
  console.log('  USDT  :', usdtAddress)
  console.log('  Escrow:', escrowAddress)
  console.log('────────────────────────────────────────')
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
